import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * (Component) Large image
 * Id: 1a04d7d0-79f9-481f-a260-48c113646e91
 * Codename: _component__large_image
 */
export type ComponentLargeImage = IContentItem<{
  /**
   * Image (asset)
   * Required: true
   * Id: c4286d22-d383-4270-bb4f-64f724c93d6d
   * Codename: image
   */
  image: Elements.AssetsElement;
}>;
