import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Homepage
 * Id: 3cdfd3c3-00d1-4833-bb54-81c8d282b05f
 * Codename: homepage
 */
export type Homepage = IContentItem<{
  /**
   * Text (rich_text)
   * Required: false
   * Id: d4a630b8-d4ef-4651-9cd6-f125e8344739
   * Codename: text
   */
  text: Elements.RichTextElement;
}>;
