/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Focus
 * Id: c27214b6-fb52-41ab-bd67-6299d7109a81
 * Codename: focus
 */
export type Focus =
  | '_net'
  | 'content_management'
  | 'devops'
  | 'javascript'
  | 'security';
