/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Conference Blog
 * Environment: Production
 * Project Id: 5faadba4-74cb-0112-28d6-1af374974337
 */
export const assetFolders = {} as const;
