/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Conference Blog
 * Environment: Production
 * Project Id: 5faadba4-74cb-0112-28d6-1af374974337
 */
export const contentTypes = {
  /**
   * (Component) Conference
   * Last modified: Fri Oct 14 2022 07:56:27 GMT+0200 (Central European Summer Time)
   */
  _component__conference: {
    codename: '_component__conference',
    id: '82ab0091-ee71-4a4a-ae7b-88f2f67fa14c',
    externalId: undefined,
    name: '(Component) Conference',
    elements: {
      /**
       * Conference (modular_content)
       */
      conference: {
        codename: 'conference',
        id: '73bbf482-1517-43f0-ad2b-29348f1885da',
        externalId: undefined,
        name: 'Conference',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Position (multiple_choice)
       */
      position: {
        codename: 'position',
        id: 'fcf43d01-d527-4cb7-ac63-7edaa70da70d',
        externalId: undefined,
        name: 'Position',
        required: true,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * (Component) CTA
   * Last modified: Fri Oct 14 2022 08:22:15 GMT+0200 (Central European Summer Time)
   */
  _component__cta: {
    codename: '_component__cta',
    id: '46c49068-c4ef-4ee2-9e85-4589eb5f4c7e',
    externalId: undefined,
    name: '(Component) CTA',
    elements: {
      /**
       * Description (text)
       */
      description: {
        codename: 'description',
        id: '38a55c4e-088e-4a1d-a641-fd6aadf99301',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Headline (text)
       */
      headline: {
        codename: 'headline',
        id: '86972137-b6cc-4a23-8bd2-d3c9e8b8c74e',
        externalId: undefined,
        name: 'Headline',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Image (asset)
       */
      image: {
        codename: 'image',
        id: '0107c942-8f0f-44bc-89ce-eb4b872e5533',
        externalId: undefined,
        name: 'Image',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Link (text)
       */
      link: {
        codename: 'link',
        id: '69265a03-0dc3-4536-a230-674315cde394',
        externalId: undefined,
        name: 'Link',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Link text (text)
       */
      link_text: {
        codename: 'link_text',
        id: 'f588d497-285e-4962-819b-4105eb9117c2',
        externalId: undefined,
        name: 'Link text',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * (Component) Large image
   * Last modified: Fri Oct 14 2022 07:56:41 GMT+0200 (Central European Summer Time)
   */
  _component__large_image: {
    codename: '_component__large_image',
    id: '1a04d7d0-79f9-481f-a260-48c113646e91',
    externalId: undefined,
    name: '(Component) Large image',
    elements: {
      /**
       * Image (asset)
       */
      image: {
        codename: 'image',
        id: 'c4286d22-d383-4270-bb4f-64f724c93d6d',
        externalId: undefined,
        name: 'Image',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * (Component) Three conferences
   * Last modified: Fri Oct 14 2022 07:56:49 GMT+0200 (Central European Summer Time)
   */
  _component__three_conferences: {
    codename: '_component__three_conferences',
    id: '7e2ae5c6-a398-4764-ba26-843526246692',
    externalId: undefined,
    name: '(Component) Three conferences',
    elements: {
      /**
       * Conferences (modular_content)
       */
      conferences: {
        codename: 'conferences',
        id: '742dc89a-89fc-4223-825a-e8e3fbaa5b86',
        externalId: undefined,
        name: 'Conferences',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       */
      description: {
        codename: 'description',
        id: '03e82b62-d164-457c-85d1-a53b7fc08bcf',
        externalId: undefined,
        name: 'Description',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Headline (text)
       */
      headline: {
        codename: 'headline',
        id: 'cc0fe303-c67a-4617-a9c4-c0fa530bbfb2',
        externalId: undefined,
        name: 'Headline',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Conference
   * Last modified: Fri Oct 14 2022 07:18:19 GMT+0200 (Central European Summer Time)
   */
  conference: {
    codename: 'conference',
    id: '62952827-a865-45c5-b884-b6fc1eb009d8',
    externalId: undefined,
    name: 'Conference',
    elements: {
      /**
       * Address (text)
       */
      address: {
        codename: 'address',
        id: '0b9efbff-cf09-4a87-b0a4-2d15462e5701',
        externalId: undefined,
        name: 'Address',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Description (rich_text)
       */
      description: {
        codename: 'description',
        id: '4e39eb4a-68bb-4444-86b5-adcaa379f3b0',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * End date (date_time)
       */
      end_date: {
        codename: 'end_date',
        id: '0f815e31-4560-4b27-be78-3a9863ed6e66',
        externalId: undefined,
        name: 'End date',
        required: false,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Focus (taxonomy)
       */
      focus: {
        codename: 'focus',
        id: '4d455ffc-b044-416c-afc8-abbff3c3f4db',
        externalId: undefined,
        name: 'Focus',
        required: true,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Name (text)
       */
      name: {
        codename: 'name',
        id: 'c2e79854-644b-45bc-9743-6a7e4c4ffa13',
        externalId: undefined,
        name: 'Name',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Start date (date_time)
       */
      start_date: {
        codename: 'start_date',
        id: '548f6ea8-6ab6-444c-be74-b220d13b4b16',
        externalId: undefined,
        name: 'Start date',
        required: false,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * URL slug (url_slug)
       */
      url_slug: {
        codename: 'url_slug',
        id: 'c6dbf547-1adf-45c1-821c-6d57fbbd765f',
        externalId: undefined,
        name: 'URL slug',
        required: true,
        type: 'url_slug',
        snippetCodename: undefined,
      },

      /**
       * Venue photo (asset)
       */
      venue_photo: {
        codename: 'venue_photo',
        id: '1f9fc8ac-bd14-4f56-a8be-34fe1f39fcf6',
        externalId: undefined,
        name: 'Venue photo',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Homepage
   * Last modified: Fri Oct 14 2022 07:51:00 GMT+0200 (Central European Summer Time)
   */
  homepage: {
    codename: 'homepage',
    id: '3cdfd3c3-00d1-4833-bb54-81c8d282b05f',
    externalId: undefined,
    name: 'Homepage',
    elements: {
      /**
       * Text (rich_text)
       */
      text: {
        codename: 'text',
        id: 'd4a630b8-d4ef-4651-9cd6-f125e8344739',
        externalId: undefined,
        name: 'Text',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },
    },
  },
} as const;
