/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Conference Blog
 * Environment: Production
 * Project Id: 5faadba4-74cb-0112-28d6-1af374974337
 */
export const languages = {
  /**
   * Default project language
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Default project language',
  },
} as const;
