/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Conference Blog
 * Environment: Production
 * Project Id: 5faadba4-74cb-0112-28d6-1af374974337
 */
export const roles = {
  /**
   * Project manager
   */
  projectManager: {
    codename: 'project-manager',
    id: '1074f289-6b8c-4c07-aded-46748c72932e',
    name: 'Project manager',
  },
} as const;
