/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Conference Blog
 * Environment: Production
 * Project Id: 5faadba4-74cb-0112-28d6-1af374974337
 */
export const taxonomies = {
  /**
   * Focus
   */
  focus: {
    codename: 'focus',
    id: 'c27214b6-fb52-41ab-bd67-6299d7109a81',
    externalId: undefined,
    name: 'Focus',
    terms: {
      _net: {
        codename: '_net',
        id: '73f3450c-1c27-4f09-9fe2-64385483f854',
        externalId: undefined,
        name: '.NET',
        terms: {},
      },
      content_management: {
        codename: 'content_management',
        id: '782e7027-4128-4ea7-b05e-4e627284e3f0',
        externalId: undefined,
        name: 'Content management',
        terms: {},
      },
      devops: {
        codename: 'devops',
        id: '0aaf5afe-6879-4047-b0f7-84ec5440579b',
        externalId: undefined,
        name: 'DevOps',
        terms: {},
      },
      javascript: {
        codename: 'javascript',
        id: 'cd4a7482-6cc2-4ec6-b29a-228fe2d6bb8a',
        externalId: undefined,
        name: 'Javascript',
        terms: {},
      },
      security: {
        codename: 'security',
        id: '68a68f3e-ffcc-4455-b91e-320357d32c0a',
        externalId: undefined,
        name: 'Security',
        terms: {},
      },
    },
  },
} as const;
