/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Conference Blog
 * Environment: Production
 * Project Id: 5faadba4-74cb-0112-28d6-1af374974337
 */
export const workflows = {
  /**
   * Default
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
} as const;
